import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    welcome: "Good Evening,",
    categories: "Categories",
    trending: "Trending Universe",
    seeAll: "DISCOVER ALL",
    nowPlaying: "Now Playing",
    downloads: "Downloads",
    history: "History",
    profile: "Profile",
    admin: "Admin",
    upload: "Publish",
    search: "Ask HabeshaCast anything...",
    language: "Language",
    amharic: "Amharic",
    english: "English",
    oromiffa: "Oromiffa",
    tigrinya: "Tigrinya",
    home: "Home",
    explore: "Explore",
    settings: "Settings",
    myUploads: "My Uploads",
    favorites: "Favorites",
    logout: "Log Out",
    adminDashboard: "Admin Dashboard",
    needsReview: "Needs Review",
    approve: "Approve",
    reject: "Reject",
    blockUser: "Block User",
    uploadStudio: "Create & Upload Audio",
    aiRecommended: "AI RECOMMENDED",
    neuralPicks: "For You – Neural Picks",
    soundOcean: "Live Sound Ocean",
    loginTitle: "Log In",
    registerTitle: "Create Account",
    fullName: "Full Name",
    email: "Email Address",
    password: "Password",
    alreadyAccount: "Already have an account? Log In",
    noAccount: "Create an Account",
    loginSubtitle: "Listen to the voices of Ethiopia",
    mostPopular: "Most Popular",
    newReleases: "New Releases",
    offlineAvailable: "Offline Available",
    noEpisodes: "No episodes found in this category yet.",
    discoverSubtitle: "Discover. Listen. Connect.",
    account: "Account",
    experience: "Experience",
    notifications: "Notifications",
    storage: "Storage & Data",
    about: "About",
    editProfile: "Edit Profile",
    security: "Security",
    twoFactor: "Two-Factor Auth",
    audioQuality: "Audio Quality",
    playbackSpeed: "Playback Speed",
    skipInterval: "Skip Interval",
    pushNotifications: "Push Notifications",
    newEpisodeAlerts: "New Episode Alerts",
    downloadWifi: "Download on Wi-Fi Only",
    clearCache: "Clear Cache",
    helpSupport: "Help & Support",
    privacyPolicy: "Privacy Policy",
    version: "Version",
    high: "High",
    normal: "Normal",
    dataSaver: "Data Saver",
    seconds: "seconds"
  },
  am: {
    welcome: "እንደምን አመሹ፣",
    categories: "ምድቦች",
    trending: "አሁን በመታየት ላይ ያሉ 🔥",
    seeAll: "ሁሉንም ይመልከቱ",
    nowPlaying: "አሁን በመጫወት ላይ",
    downloads: "የወረዱ",
    history: "ታሪክ",
    profile: "መገለጫ",
    admin: "አስተዳዳሪ",
    upload: "አዲስ ጫን",
    search: "HabeshaCast ን ይጠይቁ...",
    language: "ቋንቋ",
    amharic: "አማርኛ",
    english: "እንግሊዝኛ",
    oromiffa: "ኦሮምኛ",
    tigrinya: "ትግርኛ",
    home: "መነሻ",
    explore: "አስስ",
    settings: "ቅንብሮች",
    myUploads: "የጫንኳቸው",
    favorites: "ተወዳጆች",
    logout: "ውጣ",
    adminDashboard: "የአስተዳዳሪ ሰሌዳ",
    needsReview: "ግምገማ የሚጠብቁ",
    approve: "አጽድቅ",
    reject: "አትቀበል",
    blockUser: "ተጠቃሚውን እገድ",
    uploadStudio: "ድምጽ ይፍጠሩ እና ይጫኑ",
    aiRecommended: "በአርቲፊሻል ኢንተለጀንስ የተመከረ",
    neuralPicks: "ለእርስዎ የተመረጡ",
    soundOcean: "የቀጥታ ድምጽ ውቅያኖስ",
    loginTitle: "ግባ",
    registerTitle: "አካውንት ክፈት",
    fullName: "ሙሉ ስም",
    email: "ኢሜይል",
    password: "የይለፍ ቃል",
    alreadyAccount: "አካውንት አለዎት? ይግቡ",
    noAccount: "አዲስ አካውንት ክፈት",
    loginSubtitle: "የኢትዮጵያን ድምፆች ያዳምጡ",
    mostPopular: "ተወዳጅ",
    newReleases: "አዳዲስ",
    offlineAvailable: "ያለ ኢንተርኔት የሚሰሩ",
    noEpisodes: "በዚህ ምድብ እስካሁን ምንም የለም።",
    discoverSubtitle: "ያግኙ። ያዳምጡ። ይገናኙ።",
    account: "መለያ",
    experience: "ልምድ",
    notifications: "ማሳወቂያዎች",
    storage: "ማከማቻ እና ዳታ",
    about: "ስለ መተግበሪያው",
    editProfile: "መገለጫ አርትዕ",
    security: "ደህንነት",
    twoFactor: "ባለ ሁለት ደረጃ ማረጋገጫ",
    audioQuality: "የድምጽ ጥራት",
    playbackSpeed: "የመጫወቻ ፍጥነት",
    skipInterval: "የዝላይ ጊዜ",
    pushNotifications: "የግፊት ማሳወቂያዎች",
    newEpisodeAlerts: "የአዲስ ክፍል ማሳወቂያ",
    downloadWifi: "በዋይፋይ ብቻ አውርድ",
    clearCache: "ካሽ አጽዳ",
    helpSupport: "እርዳታ እና ድጋፍ",
    privacyPolicy: "የግላዊነት ፖሊሲ",
    version: "ስሪት",
    high: "ከፍተኛ",
    normal: "መካከለኛ",
    dataSaver: "ዳታ ቆጣቢ",
    seconds: "ሰከንዶች"
  },
  om: {
    welcome: "Akkam bultan,",
    categories: "Ramaddiiwwan",
    trending: "Amma kan jaallataman",
    seeAll: "Hundumaa ilaali",
    nowPlaying: "Amma kan taphatu",
    downloads: "Kan buufaman",
    history: "Seenaa",
    profile: "Eenyummeessaa",
    admin: "Bulchaa",
    upload: "Ol fe'i",
    search: "HabeshaCast gaafadhu...",
    language: "Afaan",
    amharic: "Amaariffa",
    english: "Ingiliffa",
    oromiffa: "Afaan Oromoo",
    tigrinya: "Tigriffa",
    home: "Mana",
    explore: "Barbaadi",
    settings: "Sirna",
    myUploads: "Fe'iinsa koo",
    favorites: "Filatamaa",
    logout: "Ba'i",
    adminDashboard: "Dallaa Bulchaa",
    needsReview: "Milaa deebii barbaadu",
    approve: "Mirkaneessi",
    reject: "Kufisi",
    blockUser: "Nama kana ittisi",
    uploadStudio: "Sagalee uumi ol fe'i",
    aiRecommended: "AI kan gorsa kennu",
    neuralPicks: "Siif kan filataman",
    soundOcean: "Garba Sagalee Kallattii",
    loginTitle: "Seeni",
    registerTitle: "Account Banu",
    fullName: "Maqaa Guutuu",
    email: "Imeeyilii",
    password: "Jecha Iccitii",
    alreadyAccount: "Account qabduu? Seenaa",
    noAccount: "Account haaraa bani",
    loginSubtitle: "Sagalee Itiyoophiyaa dhaggeeffadhu",
    mostPopular: "Baay'ee jaallataman",
    newReleases: "Haaraa kan ba'an",
    offlineAvailable: "Intarneetii malee",
    noEpisodes: "Ramaddii kana jalatti homtuu hin jiru.",
    discoverSubtitle: "Barbaadi. Dhaggeeffadhu. Wal quunnami.",
    account: "Account",
    experience: "Muuxannoo",
    notifications: "Beeksisa",
    storage: "Kuusaa fi Daataa",
    about: "Waa'ee",
    editProfile: "Eenyummeessaa jijjiiri",
    security: "Nageenya",
    twoFactor: "Mirkaneessa sadarkaa lamaa",
    audioQuality: "Qulqullina Sagalee",
    playbackSpeed: "Saffisa Taphaa",
    skipInterval: "Yeroo utaalchaa",
    pushNotifications: "Beeksisa ariifachiisaa",
    newEpisodeAlerts: "Beeksisa kutaa haaraa",
    downloadWifi: "Wi-Fi qofaan buusi",
    clearCache: "Cache qulqulleessi",
    helpSupport: "Gargaarsa fi Deeggarsa",
    privacyPolicy: "Imaammata Iccitii",
    version: "Viraajii",
    high: "Olaanaa",
    normal: "Giddu-galeessa",
    dataSaver: "Daataa qusataa",
    seconds: "sekondii"
  },
  ti: {
    welcome: "ከመይ ኣምሲኹም፣",
    categories: "ዓይነታት",
    trending: "ሕጂ ዝርአዩ ዘለዉ",
    seeAll: "ኩሉ ርአ",
    nowPlaying: "ሕጂ ዝጻወት ዘሎ",
    downloads: "ዝወረዱ",
    history: "ታሪኽ",
    profile: "ፕሮፋይል",
    admin: "ኣመሓዳሪ",
    upload: "ፅዓን",
    search: "ን HabeshaCast ሕተቱ...",
    language: "ቋንቋ",
    amharic: "ኣምሓርኛ",
    english: "እንግሊዝኛ",
    oromiffa: "ኦሮምኛ",
    tigrinya: "ትግርኛ",
    home: "መበገሲ",
    explore: "ኣለሽ",
    settings: "ቅንጅት",
    myUploads: "ዝጸዓንኩዎም",
    favorites: "ዝተመርጹ",
    logout: "ውጻእ",
    adminDashboard: "ቦርድ ኣመሓዳሪ",
    needsReview: "ክግምገሙ ዝግበኦም",
    approve: "ኣጽድቕ",
    reject: "ኣይትቀበል",
    blockUser: "ንተጠቃሚ ዕጾ",
    uploadStudio: "ድምጺ ፈጢርካ ፅዓን",
    aiRecommended: "ብ AI ዝተመከረ",
    neuralPicks: "ንዓኻ ዝተመርጹ",
    soundOcean: "ውቅያኖስ ድምጺ",
    loginTitle: "እቶ",
    registerTitle: "ኣካውንት ክፈት",
    fullName: "ምሉእ ስም",
    email: "ኢሜይል",
    password: "መሕለፊ ቃል",
    alreadyAccount: "ኣካውንት ኣለካ ድዩ? እቶ",
    noAccount: "ሓድሽ ኣካውንት ክፈት",
    loginSubtitle: "ድምጺ ኢትዮጵያ ስምዑ",
    mostPopular: "ዝተመርጹ",
    newReleases: "ሓደስቲ",
    offlineAvailable: "ብዘይ ኢንተርኔት ዝሰርሑ",
    noEpisodes: "ኣብዚ ዓይነት ዝተረኸበ የለን።",
    discoverSubtitle: "ርኸብ። ስማዕ። ተራኸብ።",
    account: "ኣካውንት",
    experience: "ተመኩሮ",
    notifications: "መፍለጥታታት",
    storage: "መኽዘንን ዳታን",
    about: "ብዛዕባ",
    editProfile: "ፕሮፋይል ኣስተኻኽል",
    security: "ደሕንነት",
    twoFactor: "ንመረጋገጺ ክልተ ደረጃ",
    audioQuality: "ጽሬት ድምጺ",
    playbackSpeed: "ቅልጣፈ መጻወቲ",
    skipInterval: "ግዜ ዝላ",
    pushNotifications: "ናይ ፑሽ መፍለጥታታት",
    newEpisodeAlerts: "ናይ ሓድሽ ክፋል መፍለጥታ",
    downloadWifi: "ብዋይፋይ ጥራይ ኣውርድ",
    clearCache: "ካሽ ኣጽሪ",
    helpSupport: "ሓገዝን ደገፍን",
    privacyPolicy: "ፖሊሲ ምስጢራውነት",
    version: "ቨርዥን",
    high: "ላዕለዋይ",
    normal: "ማእከላይ",
    dataSaver: "ዳታ ቆጣቢ",
    seconds: "ሰከንድ"
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('hc_lang') || 'am';
  });

  useEffect(() => {
    localStorage.setItem('hc_lang', language);
  }, [language]);

  const t = (key) => translations[language][key] || translations['en'][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
